# conda activate recom
#   
# conda env remove recom
# conda config --set channel_priority flexible     
# conda config --set remote_read_timeout_secs 500
# conda config --set remote_max_retries 10
# conda config --set use_index_cache True  
# conda config --set verbosity  3   

name: recom101
channels:
- fastchan
- defaults
- conda-forge
dependencies:
- python==3.8.10
- pandas==1.4.3
- numpy==1.22.4
- matplotlib==3.5.2
- scikit-learn==1.1.1
- fastai==2.7.3
- jupyter==1.0.0
- jupyterlab==3.4.3
- ipython==8.4.0
- pip==22.1.2 
- tensorflow
- lightfm==1.16
- implicit==0.5.2
- pip:  
  - ipykernel
  - loguru==0.6.0
  - lightfm_dataset_helper==0.1.2
  - adtk==0.6.2
  - streamlit==1.10.0
  - polars==0.13.51
  - pandas-gbq
  - PyGithub
  - pydantic
